# Generated by Django 2.1.3 on 2019-07-17 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(db_index=True)),
                ('date_updated', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('course_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('course_name', models.CharField(max_length=128)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator_course_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='updater_course_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course',
                'ordering': ['date_added', '-course_id'],
            },
        ),
        migrations.CreateModel(
            name='SemesterOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(db_index=True)),
                ('date_updated', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('semester_offering_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('semester_name', models.CharField(max_length=128)),
                ('start_date', models.DateField(db_index=True, null=True)),
                ('end_date', models.DateField(db_index=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base_app.Course')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator_semesteroffering_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='updater_semesteroffering_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'semester_offering',
                'ordering': ['date_added', '-semester_offering_id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(db_index=True)),
                ('date_updated', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('student_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('student_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator_student_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='updater_student_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['date_added', '-student_id'],
            },
        ),
        migrations.CreateModel(
            name='StudentCourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(db_index=True)),
                ('date_updated', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator_studentcourseregistration_objects', to=settings.AUTH_USER_MODEL)),
                ('semester_offering', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base_app.SemesterOffering')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base_app.Student')),
                ('updater', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='updater_studentcourseregistration_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_course_registration',
            },
        ),
    ]
