# Generated by Django 2.1.3 on 2019-07-18 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(db_index=True)),
                ('date_updated', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('student_name', models.CharField(max_length=128)),
                ('missed_class', models.CharField(max_length=128)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator_survey1_objects', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base_app.SemesterOffering')),
                ('updater', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='updater_survey1_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey1',
            },
        ),
    ]
