# Generated by Django 2.1.3 on 2019-07-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_survey2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='semesteroffering',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='semesteroffering',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='student',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='studentcourseregistration',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='studentcourseregistration',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='survey1',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='survey1',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='survey2',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='survey2',
            name='updater',
        ),
    ]
